20240119 aktuelle projekte jan 2
kivitendo/kivitendo-erp pull request #316
Opened 2024-04-12 11:48 UTC by jbueren

2024-04-16 08:48 UTC, bblessmann requested changes
Sieht gut aus. Ein paar Kleinigkeiten habe ich kommentiert. Und:
* abschließender locales-Lauf en fehlt (erst am Ende machen und "de" auch nochmal - kommt vermutlich noch eine Änderung rein wegen der Erweiterung auf 20 Positionen im Mini-Journal im Template fürs design40).
* in einer commit-Message ist ein Bezug auf einen commit-Hash. Ich finde es besser, sich hier auf die andere Message zu beziehen, da sich der Hash nach dem rebase und merge ändern wird

2024-04-16 08:48 UTC, bblessmann commented on templates/webpages/inventory/_journal.html
> +<h3>[% 'Journal of Last 20 Transfers' | $T8 %]</h3>
Die Änderung auf 20 letze Einträge fehlt im design40-Template.

2024-04-16 08:48 UTC, bblessmann commented on SL/DB/Helper/Payment.pm
>    # then return true
Dieser Kommentar scheint von vorher noch übrig geblieben zu sein.

2024-04-16 08:48 UTC, bblessmann commented on doc/changelog
> +    angeboten, die alle bie den Buchungen hinterlegten PDF-Belege in einem PDF bündelt.
Typo: "bei" statt "bie"

2024-04-16 08:48 UTC, bblessmann commented on bin/mozilla/sepa.pl
> +  my $form     =  $main::form;
Ausrichtung

2024-04-16 08:48 UTC, bblessmann commented on bin/mozilla/sepa.pl
> +  my $locale   =  $main::locale;
Ausrichtung

2024-04-16 08:48 UTC, bblessmann commented on bin/mozilla/sepa.pl
> +    my $export = SL::SEPA->retrieve_export('id' => $id, 'details' => 1, vc => $vc);
hier würde ich entweder alle keys der benannten Parameter in Hochkomma setzen oder keine. Keine würde ich bevorzugen:
SL::SEPA->retrieve_export(id => $id, details => 1, vc => $vc);

2024-04-16 08:48 UTC, bblessmann commented on bin/mozilla/sepa.pl
> +
Ich hab's jetzt nicht probiert, aber die letzten Zeilen scheinen mir evtl. durch eine Kombination aus
SL::Helper::CreatePDF->merge_pdfs und SL::Controller::Base->send_file ersetzbar zu sein. Ist nur eine Idee.

2024-04-16 08:48 UTC, bblessmann commented on locale/de/all
> +  'Cannot calculate Amount and Tax for this booking correctly, please check chart settings' => 'Kann nicht den Skonto-Betrag Brutto und netto kalkulieren. Bitte prüfen Sie die entsprechenden Kontenko
Die deutsche Übersetzung finde ich etwas sperrig. Zumindest sagt sie aber was anderes als der  englische Text. Und Brutto evtl. auch klein.

2024-04-16 08:48 UTC, bblessmann commented on templates/design40_webpages/inventory/_journal.html
> +        <td>[% row.base.oe_id | html %][% row.base.invoice.invoice.invnumber | html %]</td>
Wenn Du sowas machts, dann bekommst Du direkt einen Link, falls das gewünscht ist.
[% USE P %]
...
<td>[% IF row.base.oe; P.delivery_order.delivery_order(row.base.oe); END %][% IF row.base.invoice; P.invoice.invoice(row.base.invoice.invoice); END %]</td>

2024-04-16 08:48 UTC, bblessmann commented on templates/webpages/part/_basic_data.html
> +            [% L.select_tag('part.bin_id', SELF.part.warehouse.bins_sorted_naturally, default=SELF.part.bin.id, title_key='description', with_empty=0, class='wi-lightwide') %]
Ich glaube, die css-Klasse 'wi-lightwide' gibt es nicht im alten Design.

2024-04-16 08:48 UTC, bblessmann commented on templates/webpages/inventory/_journal.html
> +  <td>[% row.base.oe_id | html %][% row.base.invoice.invoice.invnumber | html %]</td>
siehe Kommentar zur Datei  im design40

2024-04-16 08:48 UTC, bblessmann commented on t/db_helper/payment.t
> +  is($invoice2->within_skonto_period(transdate => DateTime->now()->add(days => 6)), ''); # not within skonto period
Sollte die Testnachricht nicht mit an "is" übergeben werden, statt als Kommentar?

2024-05-16 16:53 UTC, jbueren commented on SL/DB/Helper/Payment.pm
>    # then return true
Den Kommentar hab ich bewußt zusätzlich da angebracht und war vorher nicht da.

2024-05-16 16:55 UTC, jbueren commented on bin/mozilla/sepa.pl
> +  my $form     =  $main::form;
ed43b157f0

2024-05-16 16:56 UTC, jbueren commented on bin/mozilla/sepa.pl
> +    my $export = SL::SEPA->retrieve_export('id' => $id, 'details' => 1, vc => $vc);
1a54cb45e1

2024-05-16 17:03 UTC, jbueren commented on bin/mozilla/sepa.pl
> +
Die Idee ist nicht schlecht, ich hab mich eher an den Code in DN.pm orientiert, da es der einzige Aufruf von ghostscript ist.

Ich lass es in dem Zweig so, aber gut wäre ein refactoren dann hier und in DN:
https://www.kivitendo.de/redmine/issues/689

2024-05-16 17:03 UTC, jbueren commented on doc/changelog
> +    angeboten, die alle bie den Buchungen hinterlegten PDF-Belege in einem PDF bündelt.
4596a0a2e4

2024-05-16 17:08 UTC, jbueren commented on locale/de/all
> +  'Cannot calculate Amount and Tax for this booking correctly, please check chart settings' => 'Kann nicht den Skonto-Betrag Brutto und netto kalkulieren. Bitte prüfen Sie die entsprechenden Kontenko
86f7433fdb
Ich probier in Zukunft in englisch präziser zu formulieren. Eigentlich geht es bei dieser Meldung darum, dass bei Skonto-Korrekturen Betrag und Steuer abweichen und ggf. einfach Skonto-Automatiken falsch konfiguriert sein könnten

2024-05-16 17:17 UTC, jbueren commented on templates/webpages/inventory/_journal.html
> +<h3>[% 'Journal of Last 20 Transfers' | $T8 %]</h3>
Schlampig, schlampig. Fehlt jetzt nicht mehr f69c413ec4

2024-05-16 17:21 UTC, jbueren commented on templates/webpages/part/_basic_data.html
> +            [% L.select_tag('part.bin_id', SELF.part.warehouse.bins_sorted_naturally, default=SELF.part.bin.id, title_key='description', with_empty=0, class='wi-lightwide') %]
stimmt

2024-05-21 13:25 UTC, bblessmann commented on SL/DB/Helper/Payment.pm
>    # then return true
Ich meinte den Kommentar "# then return true". Der war vorher da und ergibt meiner Meinung nach so keinen Sinn, da ja jetzt auch "false" zurückgegeben werden kann.

2024-05-21 13:39 UTC, bblessmann requested changes
Sieht gut aus - nur noch der falsche Kommentar in Payment.pm ("the return true")

2024-05-22 07:48 UTC, bblessmann approved these changes
Super

2024-05-22 07:49 UTC, bblessmann commented
Ich mache ein rebase wg. des Konflikts und merge den Branch.

2024-05-22 10:37 UTC, merged